DELETE FROM resources WHERE route_path = '/lab/bydp' OR title = '半圆拼合实验室';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('半圆拼合实验室', '图形与几何', '通用', '/uploads/collections/edu-covers/bydp.png', '半圆拼合实验室，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/bydp.html', '/lab/bydp', 'html');
DELETE FROM resources WHERE route_path = '/lab/cft' OR title = '长方体观察台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('长方体观察台', '图形与几何', '通用', '/uploads/collections/edu-covers/cft.png', '长方体观察台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/cft.html', '/lab/cft', 'html');
DELETE FROM resources WHERE route_path = '/lab/czxd' OR title = '垂线比较观测台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('垂线比较观测台', '图形与几何', '通用', '/uploads/collections/edu-covers/czxd.png', '垂线比较观测台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/czxd.html', '/lab/czxd', 'html');
DELETE FROM resources WHERE route_path = '/lab/dbx' OR title = '面积转化实验室';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('面积转化实验室', '图形与几何', '通用', '/uploads/collections/edu-covers/dbx.png', '面积转化实验室，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/dbx.html', '/lab/dbx', 'html');
DELETE FROM resources WHERE route_path = '/lab/fenshu' OR title = '分数墙探索台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('分数墙探索台', '数与代数', '通用', '/uploads/collections/edu-covers/fenshu.png', '分数墙探索台，围绕数量关系、运算规律与结构理解设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/fenshu.html', '/lab/fenshu', 'html');
DELETE FROM resources WHERE route_path = '/lab/hgz' OR title = '果汁浓度推理站';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('果汁浓度推理站', '数与代数', '通用', '/uploads/collections/edu-covers/hgz.png', '果汁浓度推理站，围绕数量关系、运算规律与结构理解设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/hgz.html', '/lab/hgz', 'html');
DELETE FROM resources WHERE route_path = '/lab/hzrj' OR title = '纸盒容积调优台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('纸盒容积调优台', '图形与几何', '通用', '/uploads/collections/edu-covers/hzrj.png', '纸盒容积调优台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/hzrj.html', '/lab/hzrj', 'html');
DELETE FROM resources WHERE route_path = '/lab/jcfx' OR title = '网格裁剪推演台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('网格裁剪推演台', '图形与几何', '通用', '/uploads/collections/edu-covers/jcfx.png', '网格裁剪推演台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/jcfx.html', '/lab/jcfx', 'html');
DELETE FROM resources WHERE route_path = '/lab/ldjl' OR title = '路线拆分计数台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('路线拆分计数台', '综合实践', '通用', '/uploads/collections/edu-covers/ldjl.png', '路线拆分计数台，结合情境任务与策略推演设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/ldjl.html', '/lab/ldjl', 'html');
DELETE FROM resources WHERE route_path = '/lab/ltxl' OR title = '双通道拼接验证台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('双通道拼接验证台', '图形与几何', '通用', '/uploads/collections/edu-covers/ltxl.png', '双通道拼接验证台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/ltxl.html', '/lab/ltxl', 'html');
DELETE FROM resources WHERE route_path = '/lab/ltzx' OR title = '直线关系校验台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('直线关系校验台', '图形与几何', '通用', '/uploads/collections/edu-covers/ltzx.png', '直线关系校验台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/ltzx.html', '/lab/ltzx', 'html');
DELETE FROM resources WHERE route_path = '/lab/lu' OR title = '网格最短路径台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('网格最短路径台', '图形与几何', '通用', '/uploads/collections/edu-covers/lu.png', '网格最短路径台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/lu.html', '/lab/lu', 'html');
DELETE FROM resources WHERE route_path = '/lab/mjyd' OR title = '等面积边界实验场';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('等面积边界实验场', '图形与几何', '通用', '/uploads/collections/edu-covers/mjyd.png', '等面积边界实验场，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/mjyd.html', '/lab/mjyd', 'html');
DELETE FROM resources WHERE route_path = '/lab/moshu' OR title = '数字卡策略局';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('数字卡策略局', '互动游戏', '通用', '/uploads/collections/edu-covers/moshu.png', '数字卡策略局，用游戏化方式组织数学互动，保留原有规则、反馈与主要交互路径。', '/uploads/collections/edu-ai-apps/moshu.html', '/lab/moshu', 'html');
DELETE FROM resources WHERE route_path = '/lab/nyr' OR title = '年月日观察器';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('年月日观察器', '综合实践', '通用', '/uploads/collections/edu-covers/nyr.png', '年月日观察器，结合情境任务与策略推演设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/nyr.html', '/lab/nyr', 'html');
DELETE FROM resources WHERE route_path = '/lab/pjf' OR title = '均分投放训练场';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('均分投放训练场', '数与代数', '通用', '/uploads/collections/edu-covers/pjf.png', '均分投放训练场，围绕数量关系、运算规律与结构理解设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/pjf.html', '/lab/pjf', 'html');
DELETE FROM resources WHERE route_path = '/lab/pxsbx' OR title = '平行四边形校准台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('平行四边形校准台', '图形与几何', '通用', '/uploads/collections/edu-covers/pxsbx.png', '平行四边形校准台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/pxsbx.html', '/lab/pxsbx', 'html');
DELETE FROM resources WHERE route_path = '/lab/sdjqr' OR title = '覆盖路径推演台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('覆盖路径推演台', '图形与几何', '通用', '/uploads/collections/edu-covers/sdjqr.png', '覆盖路径推演台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/sdjqr.html', '/lab/sdjqr', 'html');
DELETE FROM resources WHERE route_path = '/lab/shuitong' OR title = '量水调度台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('量水调度台', '综合实践', '通用', '/uploads/collections/edu-covers/shuitong.png', '量水调度台，结合情境任务与策略推演设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/shuitong.html', '/lab/shuitong', 'html');
DELETE FROM resources WHERE route_path = '/lab/sjc' OR title = '三角尺操作台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('三角尺操作台', '图形与几何', '通用', '/uploads/collections/edu-covers/sjc.png', '三角尺操作台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/sjc.html', '/lab/sjc', 'html');
DELETE FROM resources WHERE route_path = '/lab/sjxsg' OR title = '旋转寻迹实验台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('旋转寻迹实验台', '图形与几何', '通用', '/uploads/collections/edu-covers/sjxsg.png', '旋转寻迹实验台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/sjxsg.html', '/lab/sjxsg', 'html');
DELETE FROM resources WHERE route_path = '/lab/sys' OR title = '立体方块盘点台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('立体方块盘点台', '图形与几何', '通用', '/uploads/collections/edu-covers/sys.png', '立体方块盘点台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/sys.html', '/lab/sys', 'html');
DELETE FROM resources WHERE route_path = '/lab/syx' OR title = '数形结构推演台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('数形结构推演台', '数与代数', '通用', '/uploads/collections/edu-covers/syx.png', '数形结构推演台，围绕数量关系、运算规律与结构理解设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/syx.html', '/lab/syx', 'html');
DELETE FROM resources WHERE route_path = '/lab/szbm' OR title = '身份信息解码台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('身份信息解码台', '综合实践', '通用', '/uploads/collections/edu-covers/szbm.png', '身份信息解码台，结合情境任务与策略推演设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/szbm.html', '/lab/szbm', 'html');
DELETE FROM resources WHERE route_path = '/lab/szhrd' OR title = '数字滑块挑战台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('数字滑块挑战台', '互动游戏', '通用', '/uploads/collections/edu-covers/szhrd.png', '数字滑块挑战台，用游戏化方式组织数学互动，保留原有规则、反馈与主要交互路径。', '/uploads/collections/edu-ai-apps/szhrd.html', '/lab/szhrd', 'html');
DELETE FROM resources WHERE route_path = '/lab/tjsm' OR title = '对策推演实验室';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('对策推演实验室', '综合实践', '通用', '/uploads/collections/edu-covers/tjsm.png', '对策推演实验室，结合情境任务与策略推演设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/tjsm.html', '/lab/tjsm', 'html');
DELETE FROM resources WHERE route_path = '/lab/wzft' OR title = '正方体折叠工坊';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('正方体折叠工坊', '图形与几何', '通用', '/uploads/collections/edu-covers/wzft.png', '正方体折叠工坊，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/wzft.html', '/lab/wzft', 'html');
DELETE FROM resources WHERE route_path = '/lab/wzq' OR title = '坐标五子棋练习场';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('坐标五子棋练习场', '互动游戏', '通用', '/uploads/collections/edu-covers/wzq.png', '坐标五子棋练习场，用游戏化方式组织数学互动，保留原有规则、反馈与主要交互路径。', '/uploads/collections/edu-ai-apps/wzq.html', '/lab/wzq', 'html');
DELETE FROM resources WHERE route_path = '/lab/xiaogou' OR title = '拴点活动范围台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('拴点活动范围台', '图形与几何', '通用', '/uploads/collections/edu-covers/xiaogou.png', '拴点活动范围台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/xiaogou.html', '/lab/xiaogou', 'html');
DELETE FROM resources WHERE route_path = '/lab/xlmj' OR title = '铺路面积验证台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('铺路面积验证台', '图形与几何', '通用', '/uploads/collections/edu-covers/xlmj.png', '铺路面积验证台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/xlmj.html', '/lab/xlmj', 'html');
DELETE FROM resources WHERE route_path = '/lab/ygdf' OR title = '圆周展开测量台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('圆周展开测量台', '图形与几何', '通用', '/uploads/collections/edu-covers/ygdf.png', '圆周展开测量台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/ygdf.html', '/lab/ygdf', 'html');
DELETE FROM resources WHERE route_path = '/lab/yinshu' OR title = '因数分布观察台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('因数分布观察台', '数与代数', '通用', '/uploads/collections/edu-covers/yinshu.png', '因数分布观察台，围绕数量关系、运算规律与结构理解设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/yinshu.html', '/lab/yinshu', 'html');
DELETE FROM resources WHERE route_path = '/lab/ymj' OR title = '圆面积展开推演台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('圆面积展开推演台', '图形与几何', '通用', '/uploads/collections/edu-covers/ymj.png', '圆面积展开推演台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/ymj.html', '/lab/ymj', 'html');
DELETE FROM resources WHERE route_path = '/lab/yqdph' OR title = '平衡关系观察台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('平衡关系观察台', '数与代数', '通用', '/uploads/collections/edu-covers/yqdph.png', '平衡关系观察台，围绕数量关系、运算规律与结构理解设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/yqdph.html', '/lab/yqdph', 'html');
DELETE FROM resources WHERE route_path = '/lab/yuanrao' OR title = '环绕轨迹比较台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('环绕轨迹比较台', '图形与几何', '通用', '/uploads/collections/edu-covers/yuanrao.png', '环绕轨迹比较台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/yuanrao.html', '/lab/yuanrao', 'html');
DELETE FROM resources WHERE route_path = '/lab/yuanzy' OR title = '同心圆量感比较台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('同心圆量感比较台', '图形与几何', '通用', '/uploads/collections/edu-covers/yuanzy.png', '同心圆量感比较台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/yuanzy.html', '/lab/yuanzy', 'html');
DELETE FROM resources WHERE route_path = '/lab/yybfzc1' OR title = '三角周长拆解台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('三角周长拆解台', '图形与几何', '通用', '/uploads/collections/edu-covers/yybfzc1.png', '三角周长拆解台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/yybfzc1.html', '/lab/yybfzc1', 'html');
DELETE FROM resources WHERE route_path = '/lab/yysgx' OR title = '余数除法结构台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('余数除法结构台', '数与代数', '通用', '/uploads/collections/edu-covers/yysgx.png', '余数除法结构台，围绕数量关系、运算规律与结构理解设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/yysgx.html', '/lab/yysgx', 'html');
DELETE FROM resources WHERE route_path = '/lab/zcyd' OR title = '等周面积极值台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('等周面积极值台', '图形与几何', '通用', '/uploads/collections/edu-covers/zcyd.png', '等周面积极值台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/zcyd.html', '/lab/zcyd', 'html');
DELETE FROM resources WHERE route_path = '/lab/zfsjyd' OR title = '图形追及演示台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('图形追及演示台', '图形与几何', '通用', '/uploads/collections/edu-covers/zfsjyd.png', '图形追及演示台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/zfsjyd.html', '/lab/zfsjyd', 'html');
DELETE FROM resources WHERE route_path = '/lab/zhijing' OR title = '圆内线段比较台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('圆内线段比较台', '图形与几何', '通用', '/uploads/collections/edu-covers/zhijing.png', '圆内线段比较台，围绕图形观察、变换与度量设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/zhijing.html', '/lab/zhijing', 'html');
DELETE FROM resources WHERE route_path = '/lab/zhishu' OR title = '质数分组实验室';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('质数分组实验室', '数与代数', '通用', '/uploads/collections/edu-covers/zhishu.png', '质数分组实验室，围绕数量关系、运算规律与结构理解设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/zhishu.html', '/lab/zhishu', 'html');
DELETE FROM resources WHERE route_path = '/lab/zxc' OR title = '传动比观察台';
INSERT INTO resources (title, category, grade, image_url, description, file_path, route_path, resource_type) VALUES ('传动比观察台', '综合实践', '通用', '/uploads/collections/edu-covers/zxc.png', '传动比观察台，结合情境任务与策略推演设计互动任务，保留原有核心演示与操作。', '/uploads/collections/edu-ai-apps/zxc.html', '/lab/zxc', 'html');
